services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-01/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-01/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    depends_on:
      - clickhouse-keeper

  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    volumes:
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-02/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-02/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8124:8123"
      - "127.0.0.1:9001:9000"
    depends_on:
      - clickhouse-keeper

  clickhouse-03:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-03
    hostname: clickhouse-03
    volumes:
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-03/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-03/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8125:8123"
      - "127.0.0.1:9002:9000"
    depends_on:
      - clickhouse-keeper

  clickhouse-04:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-04
    hostname: clickhouse-04
    volumes:
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-04/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-04/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
        - "127.0.0.1:8126:8123"
        - "127.0.0.1:9003:9000"
    depends_on:
      - clickhouse-keeper

  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
     - ./clickhouse_cluster_2_shards_2_replicas/clickhouse-keeper/config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "9181:9181"
