services:
  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
#      - ./homework/task_14/config.xml:/etc/clickhouse-server/config.d/extra.xml
      - ./homework/task_18/config.xml:/etc/clickhouse-server/config.d/kafka.xml
      - clickhouse_data:/var/lib/clickhouse
      - ./migrations:/docker-entrypoint-initdb.d
      - ./clickhouse_extra:/etc/clickhouse-server/users.d
#     - ./homework/task_14/clickhouse-backup-config.yml:/opt/clickhouse/clickhouse-backup-config.yml
#      - ./clickhouse_server_extra:/etc/clickhouse-server/config.d
#      - ./clickhouse_udf:/etc/clickhouse-server/user_defined_executable_functions
#      - ./homework/task_5:/opt/clickhouse/udf
#      - ./homework/task_8:/var/lib/clickhouse/user_files
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    restart: unless-stopped

  s3:
    image: minio/minio:latest
    container_name: s3
    environment:
      MINIO_ROOT_USER: clickhouse
      MINIO_ROOT_PASSWORD: clickhouse_secret
    profiles:
      - donotstart
    ports:
      - "10000:10000"
      - "10001:10001"
    command: server /data --address :10000 --console-address :10001
    volumes:
      - s3_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  createbuckets:
    image: minio/mc
    profiles:
      - donotstart
    depends_on:
      s3:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://s3:10000 clickhouse clickhouse_secret;
      /usr/bin/mc admin info myminio;
      /usr/bin/mc mb --ignore-existing myminio/clickhouse;
      /usr/bin/mc anonymous set public myminio/clickhouse;
      exit 0;
      "

  zookeeper:
    platform: linux/x86_64
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    platform: linux/x86_64
    container_name: kafka1
    hostname: kafka1
    image: confluentinc/cp-kafka:latest
    profiles:
      - donotstart
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1

  postgres:
    platform: linux/x86_64
    image: aa8y/postgres-dataset:dellstore
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "psql", "-d", "dellstore", "-c", "SELECT 1 FROM pg_database WHERE datname = 'dellstore';" ]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-worker
    hostname: airflow-worker
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW_CONN_POSTGRES_DELLSTORE=postgres://postgres:postgres@postgres:5432/dellstore
      - AIRFLOW_CONN_CLICKHOUSE_DEFAULT=clickhouse://baseline_user:baseline_pass@clickhouse/default
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./homework/task_17/airflow:/opt/airflow/dags

volumes:
  clickhouse_data:
  s3_data:
