services:
  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./migrations:/docker-entrypoint-initdb.d
      - ./clickhouse_extra:/etc/clickhouse-server/users.d
      - ./clickhouse_server_extra:/etc/clickhouse-server/config.d
      - ./clickhouse_udf:/etc/clickhouse-server/user_defined_executable_functions
      - ./homework/task_5:/opt/clickhouse/udf
      - ./homework/task_8:/var/lib/clickhouse/user_files
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    restart: unless-stopped

volumes:
  clickhouse_data:
